[functions]
node_bundler = "esbuild"
external_node_modules = ["@11ty/eleventy-fetch"]

[dev]
targetPort = 8080

[[redirects]]
from = "/work/tracks/"
to = "/.netlify/functions/serverless"
status = 200
force = true